### ISSUE TITLE
feat: dropzone - highlight and spinner

### ISSUE THREAD

**Issue by peterpeterparker** [BrunnerLivio/screenbean.brunnerliv.io#5]
Hey Livio,

I had two ideas regarding the "dropzone" while trying your tool again:

- when dragging a file `over` the dropzone, would be cool to notice that the image can be dropped ("onDragOver -> highlight dropzone")

- while the image is processed, displaying some sort of `spinner` (or other cool animation) would gives a user feedback than it is going further

Cheers
David

**Comment by BrunnerLivio** [comment]
Going points, should be fairly easy to implement :)

**Comment by BrunnerLivio** [comment]
It's up and running :)

**Comment by peterpeterparker** [comment]
Nice 👍
