### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by Dev-Jago** [BrunnerLivio/screenbean.brunnerliv.io#7]
Hello! I would really like to try out your application, but when I hit yarn start the program opens up a browser page that fails to load with an error. The error is ERR_CONNECTION_REFUSED

**Comment by BrunnerLivio** [comment]
If you want to visit the page I'd encourage visiting [screenbean.brunnerliv.io](https://screenbean.brunnerliv.io)

If you want to open it up locally, just follow the README.md. With the following versions I was able to do a clean install and run it:

```
➜ node --version
v16.20.1
➜ yarn --version
1.22.21
```
